name: "Publish version"

on:
  push:
    branches: ["master"]

env:
  GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    steps:
      - id: create_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: 122445
          private_key: ${{ secrets.BOT_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ steps.create_token.outputs.token }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Publish
        run: |
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ steps.create_token.outputs.token }}
          GH_TOKEN: ${{ steps.create_token.outputs.token }}
